# Generated by Django 2.2.8 on 2020-01-23 04:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20200122_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='image',
            new_name='check_in_image',
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_image',
            field=models.ImageField(default=datetime.datetime(2020, 1, 23, 9, 51, 27, 973203), upload_to='employees images'),
            preserve_default=False,
        ),
    ]
