# Generated by Django 2.2.8 on 2020-01-24 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_auto_20200123_0951'),
    ]

    operations = [
        migrations.DeleteModel(
            name='images',
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'check_in')},
        ),
    ]
